name: "Pull Request"

on:
  pull_request:
    branches:
      - 'main'
      - 'master'
      - 'DIC1-*'
      - 'IS-*'

jobs:
  ci-checks:
    runs-on: ubuntu-latest

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important pour sonar et historique git complet

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Scan secrets with Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .github/.gitleaks.toml

      - name: Dependency vulnerability check (OWASP)
        run: mvn org.owasp:dependency-check-maven:check -P cve

      - name: Run unit tests
        run: mvn test -Put -Pit

      - name: SonarCloud Analysis
        run: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=absa550_todos \
          -Dsonar.organization=absa550 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Wait and check SonarCloud Quality Gate
        uses: sonarsource/sonarcloud-quality-gate-action@v2.1.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
